## Atividade 20 - Migração e Integração de Bases de Dados

A SoulCode Academy utiliza dois sistemas distintos para cadastro de vendas, um em sua matriz e outro em suas filiais. O sistema da matriz utiliza um db noSQL enquanto os das filiais ainda utilizam um SQL. As tabelas a seguir são amostras de dados dos dois tipos de db enviadas para auxiliar seu desenvolvimento. Crie uma db em SQL e uma noSQL, e adicione essas amostrar para criar um ambiente simulando o problema real. A seguir crie um código em Python que leia a db SQL, corrija, padronize e insira os dados na db noSQL.

Devem ser entregues:
- os códigos desenvolvidos
- um cronograma apresentando quem fez o que e quando
- uma apresentação em slides apresentando o desenvolvimento criado

### Instalações das bibliotecas

### Importações das bibliotecas

In [1]:
try:
    from google.cloud import storage
    import google.cloud.storage
    import json
    import csv
    import os
    import sys
    import pandas as pd
    import numpy as np
except Exception as e:
    print("Error : {'Falha Imports'} ".format(e))

### Conectores

In [2]:
#CONFIGURAÇÃO DA CHAVE DE SEGURANÇA
serviceAccount = 'C://Cursos//Soulcode//AuthKey//quantum-pilot-349020-5b36e5952629.json'

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount

In [3]:
#CÓDIGO QUE ACESSA A BUCKET CRIADA E FAZ O DOWNLOAD DOS ARQUIVOS VIA PANDAS
client = storage.Client()

#CRIAR UMA VARIÁVEL CHAMADA BUCKET QUE VAI RECEBER O NOME DA BUCKET DO CLOUD STORAGE
bucket = client.get_bucket('soulcodestore')

#USAR O MÉTODO BLOB PARA RETORNAR O NOME DO ARQUIVO (JSON, CSV, PARQUET)
# bucket.blob('Acessos_Banda_Larga_Fixa_2021.csv')

#CRIA UMA VARIÁVEL PATH PARA COLOCAR O CAMINHO DO CSV
#path = 'gs://datasets_pyspark/arquivo_geral.csv'
path1 = 'gs://soulcodestore/originais/Sistema_B_NoSQL.csv'
path2 = 'gs://soulcodestore/originais/Sistema_A_SQL.csv'
path3 = 'gs://soulcodestore/integrado'

### Criar Bucket no GCP e salvar os arquivos originais

In [4]:
# Download de arquivos originais para bucket - GCP 

In [5]:
## Downloading a File from Bucket

### Acessar arquivos localmente

In [6]:
# Acesso do arquivo Sistema_B_NoSQL.csv - Matriz

In [7]:
# Leitura de dados
dfA = pd.read_csv(r'C://Cursos//Soulcode//at20DE//originais//Sistema_A_SQL.csv', sep=',')

In [8]:
dfA

nota_fiscal    vendedor   total
0              1  Clarabelle  159.38
1              2        Berk  144.30
2              3        Kiri  302.49
3              4    Brigitta  381.61
4              5      Barret  277.63
..           ...         ...     ...
995          996       Ronny  577.64
996          997       Farra  434.77
997          998      Aluino  130.75
998          999       Amber  233.30
999         1000     Trumann  460.26

[1000 rows x 3 columns]

In [9]:
# Acesso do arquivo Sistema_A_SQL.csv - Filiais

In [10]:
# Leitura de dados 
dfB = pd.read_csv(r'C://Cursos//Soulcode//at20DE//originais//Sistema_A_SQL.csv', sep=',')

In [11]:
dfB

nota_fiscal    vendedor   total
0              1  Clarabelle  159.38
1              2        Berk  144.30
2              3        Kiri  302.49
3              4    Brigitta  381.61
4              5      Barret  277.63
..           ...         ...     ...
995          996       Ronny  577.64
996          997       Farra  434.77
997          998      Aluino  130.75
998          999       Amber  233.30
999         1000     Trumann  460.26

[1000 rows x 3 columns]

### Acessar arquivos do GCP

In [12]:
# Acesso do arquivo Sistema_B_NoSQL.csv - Matriz

In [13]:
gcpB = pd.read_csv(path2, sep=',')

In [14]:
gcpB

nota_fiscal    vendedor   total
0              1  Clarabelle  159.38
1              2        Berk  144.30
2              3        Kiri  302.49
3              4    Brigitta  381.61
4              5      Barret  277.63
..           ...         ...     ...
995          996       Ronny  577.64
996          997       Farra  434.77
997          998      Aluino  130.75
998          999       Amber  233.30
999         1000     Trumann  460.26

[1000 rows x 3 columns]

In [15]:
# Acesso do arquivo Sistema_A_SQL.csv - Filiais

In [16]:
gcpA = pd.read_csv(path1, sep=',')

In [17]:
gcpA

nota_fiscal     vendedor   total
0              1  Clerkclaude  260.85
1              2        Karly  217.45
2              3       Xerxes  462.32
3              4         Kaia  290.52
4              5        Myron  518.35
..           ...          ...     ...
995          996        Garey  538.00
996          997          Mil  347.70
997          998     Stefanie  199.96
998          999        Barny  595.28
999         1000          NaN  188.21

[1000 rows x 3 columns]

## Padronização - Normalização

In [18]:
# Verificação e Inspeção

In [19]:
# timing small bits of Python code
%timeit len(gcpA)
%timeit len(gcpA.index)
%timeit gcpA.shape[0]

379 ns ± 7.35 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
264 ns ± 2.38 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
644 ns ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
# timing small bits of Python code
%timeit len(gcpB)
%timeit len(gcpB.index)
%timeit gcpB.shape[0]

373 ns ± 7.23 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
266 ns ± 4.89 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
640 ns ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [21]:
len(gcpA)

1000

In [22]:
len(gcpB)

1000

In [23]:
gcpA.columns

Index(['nota_fiscal', 'vendedor', 'total'], dtype='object')

In [24]:
gcpB.columns

Index(['nota_fiscal', 'vendedor', 'total'], dtype='object')

In [25]:
gcpA.dtypes

nota_fiscal      int64
vendedor        object
total          float64
dtype: object

In [26]:
gcpB.dtypes

nota_fiscal      int64
vendedor        object
total          float64
dtype: object

In [27]:
gcpA.index

RangeIndex(start=0, stop=1000, step=1)

In [28]:
gcpB.index

RangeIndex(start=0, stop=1000, step=1)

In [29]:
gcpA.shape

(1000, 3)

In [30]:
gcpB.shape

(1000, 3)

In [31]:
gcpA.sort_values('total', ascending=False)

nota_fiscal   vendedor   total
77            78    Eugenio  598.30
56            57      Valli  598.12
803          804      Pryce  597.53
305          306      Josey  596.83
363          364     Sidnee  596.45
..           ...        ...     ...
321          322    Hartley   99.32
555          556      Danni   98.90
497          498  Gerladina   98.50
822          823  Granville   97.27
525          526     Miltie   97.25

[1000 rows x 3 columns]

In [32]:
gcpB.sort_values('total', ascending=False)

nota_fiscal   vendedor   total
119          120     Winnie  598.84
653          654    Michele  598.71
689          690       Mead  597.47
812          813   Mariette  597.15
631          632      Elsie  597.13
..           ...        ...     ...
859          860       Ivor   98.63
388          389    Frannie   98.37
140          141        NaN   98.12
900          901  Bernadina   97.69
489          490     Pattie   97.11

[1000 rows x 3 columns]

In [33]:
gcpA.sort_values('vendedor', ascending=True)

nota_fiscal vendedor   total
561          562     Abbe  194.43
109          110    Abbot  519.38
147          148  Abigale  477.34
96            97    Adams  224.31
730          731     Addi  245.93
..           ...      ...     ...
841          842      NaN  271.53
853          854      NaN  577.23
871          872      NaN  203.86
990          991      NaN  314.78
999         1000      NaN  188.21

[1000 rows x 3 columns]

In [34]:
gcpB.sort_values('vendedor', ascending=True)

nota_fiscal vendedor   total
452          453     Abba  195.55
740          741     Abie  530.95
147          148  Abigail  217.31
664          665    Abner  542.65
206          207    Adamo  389.45
..           ...      ...     ...
892          893      NaN  578.96
910          911      NaN  344.15
920          921      NaN  410.87
947          948      NaN  391.40
987          988      NaN  287.14

[1000 rows x 3 columns]

In [35]:
gcpA.values

array([[1, 'Clerkclaude', 260.85],
       [2, 'Karly', 217.45],
       [3, 'Xerxes', 462.32],
       ...,
       [998, 'Stefanie', 199.96],
       [999, 'Barny', 595.28],
       [1000, nan, 188.21]], dtype=object)

In [36]:
gcpB.values

array([[1, 'Clarabelle', 159.38],
       [2, 'Berk', 144.3],
       [3, 'Kiri', 302.49],
       ...,
       [998, 'Aluino', 130.75],
       [999, 'Amber', 233.3],
       [1000, 'Trumann', 460.26]], dtype=object)

In [37]:
gcpA.describe()

nota_fiscal        total
count  1000.000000  1000.000000
mean    500.500000   348.465440
std     288.819436   144.467192
min       1.000000    97.250000
25%     250.750000   225.700000
50%     500.500000   341.615000
75%     750.250000   470.042500
max    1000.000000   598.300000

In [38]:
gcpB.describe()

nota_fiscal        total
count  1000.000000  1000.000000
mean    500.500000   348.290770
std     288.819436   143.708767
min       1.000000    97.110000
25%     250.750000   223.832500
50%     500.500000   349.865000
75%     750.250000   472.430000
max    1000.000000   598.840000

In [39]:
somaA = gcpA['total']

In [40]:
"R$ {:,.2f}".format(somaA.sum())

'R$ 348,465.44'

In [41]:
"R$ {:,.2f}".format(somaA.mean())

'R$ 348.47'

In [42]:
somaB = gcpB['total']

In [43]:
"R$ {:,.2f}".format(somaB.sum())

'R$ 348,290.77'

In [44]:
"R$ {:,.2f}".format(somaB.mean())

'R$ 348.29'

In [45]:
# Calcula o total de linhas duplicadas em cada coluna do nosso DataFrame
# Para cada coluna,
for coluna in gcpA.columns:
    # Seleciona linhas duplicadas e as insire em um novo Dataframe
    duplicatas_df = gcpA[gcpA.duplicated(coluna)]

    # Imprime o tamanho do novo DataFrame (i.e., o número de linhas duplicadas)
    print(f"Total de linhas duplicadas "
          f"na {coluna}: {len(duplicatas_df)}")

Total de linhas duplicadas na nota_fiscal: 0
Total de linhas duplicadas na vendedor: 97
Total de linhas duplicadas na total: 9


In [46]:
# Calcula o total de linhas duplicadas em cada coluna do nosso DataFrame
# Para cada coluna,
for coluna in gcpB.columns:
    # Seleciona linhas duplicadas e as insire em um novo Dataframe
    duplicatas_df = gcpB[gcpB.duplicated(coluna)]

    # Imprime o tamanho do novo DataFrame (i.e., o número de linhas duplicadas)
    print(f"Total de linhas duplicadas "
          f"na {coluna}: {len(duplicatas_df)}")

Total de linhas duplicadas na nota_fiscal: 0
Total de linhas duplicadas na vendedor: 86
Total de linhas duplicadas na total: 9


### Verificar se todos os valores 'NaN' foram devidamente preenchidos

In [47]:
gcpA.isna()

nota_fiscal  vendedor  total
0          False     False  False
1          False     False  False
2          False     False  False
3          False     False  False
4          False     False  False
..           ...       ...    ...
995        False     False  False
996        False     False  False
997        False     False  False
998        False     False  False
999        False      True  False

[1000 rows x 3 columns]

In [48]:
gcpB.isna()

nota_fiscal  vendedor  total
0          False     False  False
1          False     False  False
2          False     False  False
3          False     False  False
4          False     False  False
..           ...       ...    ...
995        False     False  False
996        False     False  False
997        False     False  False
998        False     False  False
999        False     False  False

[1000 rows x 3 columns]

In [49]:
# Calcular o total e a porcentagem de valores ausentes

## retorna o total de valores ausentes de cada coluna
num_ausentesA = gcpA.isna().sum() 

In [50]:
num_ausentesA

nota_fiscal     0
vendedor       40
total           0
dtype: int64

In [51]:
## retorna a porcentagem de valores ausentes de cada coluna
porc_ausentesA = gcpA.isna().sum() * 100 / len(gcpA)

In [52]:
porc_ausentesA

nota_fiscal    0.0
vendedor       4.0
total          0.0
dtype: float64

In [53]:
# Cria um DataFrame com as informações computadas acima
df_ausentesA = pd.DataFrame({
    'nota_fiscal': gcpA.columns,
    'vendedor': num_ausentesA,
    'total': porc_ausentesA
})

In [54]:
df_ausentesA

nota_fiscal  vendedor  total
nota_fiscal  nota_fiscal         0    0.0
vendedor        vendedor        40    4.0
total              total         0    0.0

In [55]:
# Calcular o total e a porcentagem de valores ausentes

## retorna o total de valores ausentes de cada coluna
num_ausentesB = gcpB.isna().sum() 

In [56]:
num_ausentesB

nota_fiscal     0
vendedor       31
total           0
dtype: int64

In [57]:
## retorna a porcentagem de valores ausentes de cada coluna
porc_ausentesB = gcpB.isna().sum() * 100 / len(gcpB)

In [58]:
porc_ausentesB

nota_fiscal    0.0
vendedor       3.1
total          0.0
dtype: float64

In [59]:
porc_ausentesB

nota_fiscal    0.0
vendedor       3.1
total          0.0
dtype: float64

In [60]:
# Cria um DataFrame com as informações computadas acima
df_ausentesB = pd.DataFrame({
    'nota_fiscal': gcpB.columns,
    'vendedor': num_ausentesB,
    'total': porc_ausentesB
})

In [61]:
df_ausentesB

nota_fiscal  vendedor  total
nota_fiscal  nota_fiscal         0    0.0
vendedor        vendedor        31    3.1
total              total         0    0.0

### Imputar dados na coluna

In [62]:
# Substitui NaNs pela média de valores presentes
gcpAf = gcpA.fillna('lojaA')

In [63]:
gcpAf.values

array([[1, 'Clerkclaude', 260.85],
       [2, 'Karly', 217.45],
       [3, 'Xerxes', 462.32],
       ...,
       [998, 'Stefanie', 199.96],
       [999, 'Barny', 595.28],
       [1000, 'lojaA', 188.21]], dtype=object)

In [64]:
# Dez maiores vendas - Filiais
gcpAf.groupby("vendedor").total.sum().reset_index().sort_values("total", ascending=False).head(10)

vendedor     total
902     lojaA  13535.33
548    Mahmud   1156.40
187    Cordie   1093.99
373    Hanson   1066.78
36       Alva   1039.99
718     Regan   1031.55
626    Nancie   1019.00
385  Herschel    941.63
476     Keary    870.82
427  Jermaine    862.22

In [65]:
# Substitui NaNs pela média de valores presentes
gcpBf = gcpB.fillna('lojaB')

In [66]:
gcpBf.values

array([[1, 'Clarabelle', 159.38],
       [2, 'Berk', 144.3],
       [3, 'Kiri', 302.49],
       ...,
       [998, 'Aluino', 130.75],
       [999, 'Amber', 233.3],
       [1000, 'Trumann', 460.26]], dtype=object)

In [67]:
# Dez maiores vendas - Matriz
gcpBf.groupby("vendedor").total.sum().reset_index().sort_values("total", ascending=False).head(10)

vendedor     total
913    lojaB  11090.89
695    Paule   1191.40
802    Sibyl   1160.81
723  Randell   1073.63
45     Angie   1067.83
881   Waylan   1067.83
716    Quint   1050.15
537     Lise   1039.75
754   Rouvin    966.95
531  Leopold    915.87

### Integração dos dados - Matriz - Filiais

In [68]:
# Conveter Sistema_A_SQL.csv em .json

In [69]:
gcpAf.to_json (r'C://Cursos//Soulcode//at20DE//JSON//Sistema_A_NoSQL.json')

In [70]:
gcpAf

nota_fiscal     vendedor   total
0              1  Clerkclaude  260.85
1              2        Karly  217.45
2              3       Xerxes  462.32
3              4         Kaia  290.52
4              5        Myron  518.35
..           ...          ...     ...
995          996        Garey  538.00
996          997          Mil  347.70
997          998     Stefanie  199.96
998          999        Barny  595.28
999         1000        lojaA  188.21

[1000 rows x 3 columns]

In [71]:
gcpBf.to_json (r'C://Cursos//Soulcode//at20DE//JSON//Sistema_B_NoSQL.json')

In [72]:
gcpBf

nota_fiscal    vendedor   total
0              1  Clarabelle  159.38
1              2        Berk  144.30
2              3        Kiri  302.49
3              4    Brigitta  381.61
4              5      Barret  277.63
..           ...         ...     ...
995          996       Ronny  577.64
996          997       Farra  434.77
997          998      Aluino  130.75
998          999       Amber  233.30
999         1000     Trumann  460.26

[1000 rows x 3 columns]

### Carregamento no GCP

In [73]:
gcpAf.to_json('gs://soulcodestore/integrado/gcpAf.json')

In [74]:
gcpBf.to_json('gs://soulcodestore/integrado/gcpBf.json')

In [ ]:
# Criar novo banco integrado - JSON

In [ ]:
# Conferir dados

In [ ]:
# Salvar dados

In [ ]:
# Upload no GCP

### Criar Banco de dados - MongoDB - Sistema_B_NoSQL.csv - Matriz

In [ ]:
# Converter dados de .csv para .json

In [ ]:
# Verificar arquivo .json

In [ ]:
# Criar banco MongoDB

In [ ]:
# Inserir dados

In [ ]:
# Verificar dados

### Criar Banco de dados - Postgres -  Acesso do arquivo Sistema_A_SQL.csv - Filiais

In [ ]:
# Criar banco Postgres

In [ ]:
# Inserir dados

In [ ]:
# Verificar dados

In [ ]:
### Padronização e Normalização